### ISSUE TITLE
need some error message when API_KEY is not set

### ISSUE THREAD

**Issue by kangkyu** [LARailsLearners/youtube-search#12]

**Comment by kangkyu** [comment]
when it's not set or not correct, this error doesn't tell you need an API_KEY
```
NoMethodError: undefined method `map' for nil:NilClass
Did you mean?  tap
	from /Users/klee/practicing/laruby-study/youtube-search/lib/youtube/search/search_items.rb:8:in `items'
	from /Users/klee/practicing/laruby-study/youtube-search/lib/youtube/search.rb:32:in `get_search_items'
...
```

**Comment by Alex1100** [comment]
Could I close this issue? Check out my recent Pull Request...
